# Generated by Django 6.0.6 on 2026-06-20 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_company_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(help_text='Fecha de inicio del contrato')),
                ('end_date', models.DateField(blank=True, help_text='Fecha de finalizacion del contrato', null=True)),
                ('crop_or_activity', models.CharField(help_text='Cultivo o actividad principal del contrato', max_length=150)),
                ('land_description', models.TextField(blank=True, help_text='Descripcion del terreno o unidad productiva', null=True)),
                ('sharecropper_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Borrador', 'Borrador'), ('Activo', 'Activo'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Borrador', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(help_text='Empresa dueña de este registro de datos', on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
                ('sharecropper', models.ForeignKey(help_text='Aparcero vinculado a este contrato', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': '"contracts"."contract"',
            },
        ),
    ]
