# Generated by Django 6.0.6 on 2026-06-22 04:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharecropper',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Propietario', 'Propietario'), ('Productor Individual', 'Productor Individual'), ('Ejido', 'Ejido / Núcleo Agrario'), ('Empresa', 'Empresa / Rancho S.A.'), ('Comprador', 'Comprador Recurrente')], max_length=50)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('domicile', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_clabe', models.CharField(blank=True, max_length=18, null=True)),
                ('trust_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('state', models.CharField(choices=[('Prospecto', 'Prospecto'), ('Activo', 'Activo'), ('Bloqueado', 'Bloqueado'), ('Inactivo', 'Inactivo')], default='Prospecto', max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, help_text='Tenant al que pertenece este usuario dentro del SaaS', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='companies.company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='sharecropper_set', related_query_name='sharecropper', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='sharecropper_permissions_set', related_query_name='sharecropper', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Aparcero',
                'verbose_name_plural': 'Aparceros',
                'db_table': '"partners"."sharecropper"',
                'constraints': [models.UniqueConstraint(fields=('rfc', 'company'), name='unique_rfc_per_company')],
            },
        ),
    ]
