# Generated by Django 6.0.6 on 2026-06-14 02:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('trade_name', models.CharField(help_text='Nombre del Rancho o Empresa', max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('rfc_company', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('plan_saaS', models.CharField(choices=[('Básico', 'Básico'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise')], default='Básico', max_length=50)),
                ('subscription_status', models.CharField(choices=[('Prueba', 'Período de Prueba'), ('Activo', 'Suscripción Activa'), ('Suspendido', 'Suspendido por Falta de Pago'), ('Cancelado', 'Suscripción Cancelada')], default='Prueba', max_length=30)),
                ('animal_limit', models.IntegerField(default=100, help_text='Límite permitido por el plan')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'Company',
            },
        ),
    ]
