# Generated by Django 6.0.6 on 2026-06-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
