# Generated by Django 6.0.6 on 2026-06-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, help_text='razon social de la empresa', max_length=200, null=True),
        ),
    ]
