# Generated by Django 6.0.6 on 2026-06-22 05:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('sharecropper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': '"inventory"."group"',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('specie', models.CharField(choices=[('Bovino', 'Bovino'), ('Ovino', 'Ovino'), ('Caprino', 'Caprino'), ('Equino', 'Equino'), ('Porcino', 'Porcino')], max_length=50)),
                ('breed', models.CharField(choices=[('Angus', 'Angus'), ('Hereford', 'Hereford'), ('Holstein', 'Holstein'), ('Santa Gertrudis', 'Santa Gertrudis'), ('Charolais', 'Charolais'), ('Simmental', 'Simmental'), ('Limousin', 'Limousin')], max_length=50)),
                ('sex', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=50)),
                ('birth_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('ingression_date', models.DateField(auto_now_add=True)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='inventory.group')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
                'db_table': '"inventory"."animal"',
            },
        ),
        migrations.CreateModel(
            name='MedicalCheckup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Bad', 'Bad')], max_length=50)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('veterian_id', models.IntegerField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_checkups', to='inventory.animal')),
            ],
            options={
                'verbose_name': 'Medical Checkup',
                'verbose_name_plural': 'Medical Checkups',
                'db_table': '"inventory"."medical_checkup"',
            },
        ),
        migrations.CreateModel(
            name='Weighing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighings', to='inventory.animal')),
            ],
            options={
                'verbose_name': 'Weighing',
                'verbose_name_plural': 'Weighings',
                'db_table': '"inventory"."weighing"',
            },
        ),
    ]
