# Generated by Django 6.0.6 on 2026-07-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_veterian_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animales'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='medicalcheckup',
            options={'verbose_name': 'Revision Médica', 'verbose_name_plural': 'Revisiones Médicas'},
        ),
        migrations.AlterModelOptions(
            name='weighing',
            options={'verbose_name': 'Pesaje', 'verbose_name_plural': 'Pesajes'},
        ),
    ]
