# Generated by Django 6.0.6 on 2026-09-20 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type_sharecropper', models.CharField(choices=[('Land', 'Land'), ('Livestock', 'Livestock'), ('Agriculture', 'Agriculture')], max_length=50)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obligations', models.TextField(blank=True, null=True)),
                ('penalties', models.TextField(blank=True, null=True)),
                ('expenses_borne', models.CharField(choices=[('Sharecropper', 'Sharecropper'), ('Owner', 'Owner'), ('Both', 'Both')], max_length=50)),
                ('signature_sharecropper', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('sharecropper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Contract_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': '"contract"."contracts"',
            },
        ),
        migrations.CreateModel(
            name='Liquidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type_sharecropper', models.CharField(choices=[('Land', 'Land'), ('Livestock', 'Livestock'), ('Agriculture', 'Agriculture')], max_length=50)),
                ('liquidation_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Canceled', 'Canceled')], max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obligations', models.TextField(blank=True, null=True)),
                ('penalties', models.TextField(blank=True, null=True)),
                ('expenses_borne', models.CharField(choices=[('Sharecropper', 'Sharecropper'), ('Owner', 'Owner'), ('Both', 'Both')], max_length=50)),
                ('signature_sharecropper', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('sharecropper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Liquidation_liquidations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidation',
                'verbose_name_plural': 'Liquidations',
                'db_table': '"contract"."liquidations"',
            },
        ),
    ]
